-- ============================================================================
-- Seed Data for Real Estate Agent Application
-- Purpose: Sample listings for development and testing
-- ============================================================================
-- IMPORTANT: This file is for development/testing only
-- Do NOT run this on production database
-- ============================================================================

-- Note: Embeddings are left NULL and should be generated by the AI service
-- Geographic coordinates use PostGIS POINT format: POINT(longitude latitude)

-- ============================================================================
-- RENTAL APARTMENTS
-- ============================================================================

INSERT INTO listings (
  source,
  external_id,
  title,
  description,
  price,
  price_currency,
  listing_type,
  property_type,
  location_city,
  location_address,
  location_coordinates,
  rooms,
  bedrooms,
  bathrooms,
  surface_area,
  has_parking,
  has_balcony,
  has_garage,
  is_furnished,
  amenities,
  images,
  url
) VALUES
-- 1. Modern 2-bedroom apartment in Zagreb center
(
  'test_source',
  'test-001',
  'Spacious 2-bedroom apartment in Zagreb city center',
  'Beautiful modern apartment located in the heart of Zagreb. Fully furnished with contemporary furniture, equipped kitchen, and high-speed internet. Close to public transport, shopping centers, and restaurants. Perfect for professionals or small families.',
  800,
  'EUR',
  'rent',
  'apartment',
  'Zagreb',
  'Ilica 123',
  ST_GeomFromText('POINT(15.9819 45.8150)', 4326)::geography,  -- Zagreb center coordinates
  3,
  2,
  1,
  65.5,
  true,
  true,
  false,
  true,
  '{"elevator": true, "heating": "central", "air_conditioning": true, "internet": "fiber"}',
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'],
  'https://example.com/listing/test-001'
),

-- 2. Budget 1-bedroom apartment in Zagreb
(
  'test_source',
  'test-002',
  'Affordable 1-bedroom apartment near university',
  'Cozy apartment perfect for students or young professionals. Basic furnishing, shared laundry. Good public transport connections. Walking distance to University of Zagreb.',
  450,
  'EUR',
  'rent',
  'apartment',
  'Zagreb',
  'Savska cesta 45',
  ST_GeomFromText('POINT(15.9650 45.8050)', 4326)::geography,
  2,
  1,
  1,
  40.0,
  false,
  false,
  false,
  true,
  '{"heating": "central", "internet": "cable"}',
  ARRAY['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688'],
  'https://example.com/listing/test-002'
),

-- 3. Luxury 3-bedroom apartment in Split with sea view
(
  'test_source',
  'test-003',
  'Luxury penthouse with stunning Adriatic sea view',
  'Exclusive penthouse apartment with breathtaking sea views. Premium finishes throughout, marble bathrooms, designer kitchen with high-end appliances. Large terrace perfect for entertaining. Underground parking included. Located in prestigious area of Split.',
  1500,
  'EUR',
  'rent',
  'apartment',
  'Split',
  'Marjan 12',
  ST_GeomFromText('POINT(16.4402 43.5147)', 4326)::geography,  -- Split coordinates
  4,
  3,
  2,
  120.0,
  true,
  true,
  true,
  true,
  '{"elevator": true, "heating": "central", "air_conditioning": true, "internet": "fiber", "security": true, "pool": true}',
  ARRAY['https://images.unsplash.com/photo-1512917774080-9991f1c4c750'],
  'https://example.com/listing/test-003'
),

-- 4. Studio apartment for rent in Rijeka
(
  'test_source',
  'test-004',
  'Compact studio apartment near Rijeka port',
  'Efficient studio layout with combined living/sleeping area. Small but functional kitchen and bathroom. Ideal for single person or couple. Good value for money. Close to waterfront and city center.',
  350,
  'EUR',
  'rent',
  'apartment',
  'Rijeka',
  'Korzo 89',
  ST_GeomFromText('POINT(14.4378 45.3271)', 4326)::geography,  -- Rijeka coordinates
  1,
  NULL,  -- Studio apartments typically don't have separate bedrooms
  1,
  25.0,
  false,
  true,
  false,
  false,
  '{"heating": "electric"}',
  ARRAY['https://images.unsplash.com/photo-1560448204-603b3fc33ddc'],
  'https://example.com/listing/test-004'
),

-- ============================================================================
-- HOUSES FOR SALE
-- ============================================================================

-- 5. Family house for sale in Zagreb suburbs
(
  'test_source',
  'test-005',
  'Charming family house with large garden',
  'Beautiful detached house in quiet neighborhood. Spacious living areas, modern kitchen, four bedrooms. Large garden perfect for children and pets. Garage for two cars. Newly renovated roof and windows. Great schools nearby.',
  350000,
  'EUR',
  'sale',
  'house',
  'Zagreb',
  'Dubrava 234',
  ST_GeomFromText('POINT(16.0500 45.8300)', 4326)::geography,
  6,
  4,
  2,
  180.0,
  true,
  false,
  true,
  false,
  '{"heating": "gas", "garden": true, "basement": true}',
  ARRAY['https://images.unsplash.com/photo-1568605114967-8130f3a36994'],
  'https://example.com/listing/test-005'
),

-- 6. Luxury villa in Dubrovnik with sea access
(
  'test_source',
  'test-006',
  'Exclusive villa with private beach access',
  'Stunning Mediterranean villa with direct sea access. Infinity pool, outdoor kitchen, wine cellar. Five en-suite bedrooms, home cinema, gym. Spectacular views of Adriatic. Prime location near Old Town Dubrovnik. Perfect for luxury living or vacation rental investment.',
  1200000,
  'EUR',
  'sale',
  'house',
  'Dubrovnik',
  'Lapad 5',
  ST_GeomFromText('POINT(18.0944 42.6507)', 4326)::geography,  -- Dubrovnik coordinates
  8,
  5,
  4,
  350.0,
  true,
  true,
  true,
  true,
  '{"heating": "underfloor", "air_conditioning": true, "pool": true, "garden": true, "security": true, "sea_view": true}',
  ARRAY['https://images.unsplash.com/photo-1613490493576-7fde63acd811'],
  'https://example.com/listing/test-006'
),

-- 7. Traditional stone house in Istria
(
  'test_source',
  'test-007',
  'Authentic Istrian stone house with olive grove',
  'Beautifully restored traditional stone house. Exposed beams, stone walls, original features preserved. Large plot with 50 olive trees. Peaceful rural location with mountain views. Perfect for nature lovers or agrotourism business.',
  280000,
  'EUR',
  'sale',
  'house',
  'Pula',
  'Vodnjan 78',
  ST_GeomFromText('POINT(13.8481 44.8666)', 4326)::geography,  -- Pula coordinates
  5,
  3,
  2,
  150.0,
  true,
  false,
  false,
  false,
  '{"heating": "wood", "fireplace": true, "garden": true, "land": "5000m2"}',
  ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9'],
  'https://example.com/listing/test-007'
),

-- ============================================================================
-- OFFICE SPACES
-- ============================================================================

-- 8. Modern office space in Zagreb business district
(
  'test_source',
  'test-008',
  'Contemporary office space in premium business center',
  'Grade A office space in modern building. Open-plan layout, meeting rooms, kitchenette. High-speed internet, air conditioning, 24/7 security. Underground parking available. Excellent public transport connections. Ideal for tech companies or professional services.',
  1200,
  'EUR',
  'rent',
  'office',
  'Zagreb',
  'Avenue Mall Business Center',
  ST_GeomFromText('POINT(15.9500 45.8000)', 4326)::geography,
  4,
  NULL,  -- Office spaces don't have bedrooms
  2,
  85.0,
  true,
  false,
  false,
  false,
  '{"elevator": true, "air_conditioning": true, "internet": "fiber", "security": true, "reception": true}',
  ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c'],
  'https://example.com/listing/test-008'
),

-- ============================================================================
-- LAND FOR SALE
-- ============================================================================

-- 9. Building land near Zagreb
(
  'test_source',
  'test-009',
  'Building plot with all utilities connected',
  'Flat building plot ready for construction. Water, electricity, and sewage connections on site. Building permit in place. Quiet residential area with good infrastructure. Perfect for building your dream home.',
  120000,
  'EUR',
  'sale',
  'land',
  'Zagreb',
  'Sesvetski Kraljevec',
  ST_GeomFromText('POINT(16.1500 45.8500)', 4326)::geography,
  NULL,
  NULL,
  NULL,
  800.0,
  false,
  false,
  false,
  false,
  '{"utilities": "connected", "building_permit": true}',
  ARRAY['https://images.unsplash.com/photo-1500382017468-9049fed747ef'],
  'https://example.com/listing/test-009'
),

-- 10. Agricultural land in Slavonia
(
  'test_source',
  'test-010',
  'Fertile agricultural land suitable for crops',
  'Large agricultural plot with excellent soil quality. Suitable for various crops - corn, wheat, sunflower. Access road, water source on property. Flat terrain, easy to work. Good investment opportunity.',
  45000,
  'EUR',
  'sale',
  'land',
  'Osijek',
  'Tenja',
  ST_GeomFromText('POINT(18.6955 45.5550)', 4326)::geography,  -- Osijek coordinates
  NULL,
  NULL,
  NULL,
  15000.0,
  false,
  false,
  false,
  false,
  '{"soil": "fertile", "water": true, "access_road": true}',
  ARRAY['https://images.unsplash.com/photo-1625246333195-78d9c38ad449'],
  'https://example.com/listing/test-010'
);

-- ============================================================================
-- VERIFICATION
-- ============================================================================

-- Verify seed data was inserted
DO $$
DECLARE
  listing_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO listing_count FROM listings WHERE source = 'test_source';

  IF listing_count != 10 THEN
    RAISE WARNING 'Expected 10 test listings, found %', listing_count;
  ELSE
    RAISE NOTICE 'Successfully inserted % test listings', listing_count;
  END IF;

  -- Display summary
  RAISE NOTICE 'Seed data summary:';
  RAISE NOTICE '  - Rental apartments: %', (SELECT COUNT(*) FROM listings WHERE source = 'test_source' AND listing_type = 'rent' AND property_type = 'apartment');
  RAISE NOTICE '  - Houses for sale: %', (SELECT COUNT(*) FROM listings WHERE source = 'test_source' AND listing_type = 'sale' AND property_type = 'house');
  RAISE NOTICE '  - Office spaces: %', (SELECT COUNT(*) FROM listings WHERE source = 'test_source' AND property_type = 'office');
  RAISE NOTICE '  - Land for sale: %', (SELECT COUNT(*) FROM listings WHERE source = 'test_source' AND property_type = 'land');
END $$;

-- ============================================================================
-- NOTES
-- ============================================================================

-- To remove seed data:
-- DELETE FROM listings WHERE source = 'test_source';

-- To generate embeddings for seed data:
-- Run the embedding generation service in Phase 4

-- Coordinates are in WGS84 (SRID 4326) format: POINT(longitude latitude)
-- Note: Longitude comes FIRST in PostGIS, unlike many other systems
